### ISSUE TITLE
shared:ERROR: If pthreads and memory growth are enabled, WASM_MEM_MAX must be set

### ISSUE THREAD

**Issue by 810250082** [mpizenberg/emscripten-opencv#2]
When I perform this step: 
           `python ./platforms/js/build_js.py build_wasm --build_wasm`
there is an error:
root:WARNING: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271
shared:ERROR: If pthreads and memory growth are enabled, WASM_MEM_MAX must be set
modules/js/CMakeFiles/opencv_js.dir/build.make:179: recipe for target 'bin/opencv_js.js' failed
make[3]: *** [bin/opencv_js.js] Error 1
make[3]: Leaving directory '/home/ds/work/my_webssebly/opencv_zip/emscripten-opencv/third-party/opencv-4.1.0/build_wasm'
CMakeFiles/Makefile2:1435: recipe for target 'modules/js/CMakeFiles/opencv_js.dir/all' failed
make[2]: *** [modules/js/CMakeFiles/opencv_js.dir/all] Error 2
make[2]: Leaving directory '/home/ds/work/my_webssebly/opencv_zip/emscripten-opencv/third-party/opencv-4.1.0/build_wasm'
CMakeFiles/Makefile2:1400: recipe for target 'modules/js/CMakeFiles/opencv.js.dir/rule' failed
make[1]: *** [modules/js/CMakeFiles/opencv.js.dir/rule] Error 2
make[1]: Leaving directory '/home/ds/work/my_webssebly/opencv_zip/emscripten-opencv/third-party/opencv-4.1.0/build_wasm'
Makefile:379: recipe for target 'opencv.js' failed
make: *** [opencv.js] Error 2
Traceback (most recent call last):
  File "platforms/js/build_js.py", line 235, in <module>
    builder.build_opencvjs()
  File "platforms/js/build_js.py", line 170, in build_opencvjs
    execute(["make", "-j", str(multiprocessing.cpu_count()), "opencv.js"])
  File "platforms/js/build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 2
what should I do？

**Comment by mpizenberg** [comment]
Sorry but this was only a brief experiment I did. It only convinced me to switch to Rust for anything I want running in wasm. I should probably archive this repository.
Regarding your issue, I think following the advice of setting the `WASM_MEM_MAX` seems like the thing to do. A brief search lead me to this issue: https://github.com/opencv/opencv/issues/14691
I hope it will provide you with an answer.
Good luck!
